### ISSUE TITLE
Page doesn't render full content

### ISSUE THREAD

**Issue by SaraVieira** [ReactJSGirls/reactjsgirls-docs#9]
https://docs.reactjsgirls.com/tinder-for-cats/call-the-api

**Comment by halitogunc** [comment]
I think it is not happened to specific pages like above. You can encounter this issue for all of the pages in app except index page.  

- Re-produce:


![issue](https://user-images.githubusercontent.com/13641726/46494071-a2277580-c81a-11e8-844f-9480f05d9af9.gif)

To fix, please check out [https://github.com/ReactJSGirls/reactjsgirls-docs/pull/12](url)
